[package]
name = "day_3_toboggan_trajectory"
version = "0.1.0"
authors = ["koch_p <koch@prime-research.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
